import pandas as pd

CONCEPT_MAPPING = {
    "Assets": "assets",
    "Liabilities": "liabilities",
    "StockholdersEquity": "equity",
    "CashAndCashEquivalentsAtCarryingValue": "cash",
    "RevenueFromContractWithCustomerExcludingAssessedTax": "revenue",
    "OperatingIncomeLoss": "operating_income",
    "NetIncomeLoss": "net_income",
}

def build_financial_statements(df: pd.DataFrame) -> pd.DataFrame:
    """
    Build an annual financial statements dataset from Silver data.

    Parameters
    ----------
    df : pd.DataFrame
    Silver financial facts for one or more companies.

    Returns
    -------
    pd.DataFrame
        Annual financial statements with one row per company and
        fiscal year.
    """

    # Keep only the financial concepts required for the Gold layer.
    df = df[df["concept"].isin(CONCEPT_MAPPING)].copy()

    # Keep annual 10-K filings for the financial statement dataset.
    df = df[df["form"] == "10-K"].copy()

    # Convert SEC concept names into business-friendly column names.
    df["financial_metric"] = df["concept"].map(CONCEPT_MAPPING)

    # Create the annual financial statement structure.
    gold_df = (df.groupby(
        ["company", "company_cik", "fiscal_year", "financial_metric"], as_index=False,)["value"].last()
        .pivot(index=["company", "company_cik", "fiscal_year"], columns="financial_metric", values="value",).reset_index())

    # Remove the column-axis name generated by pivot().
    gold_df.columns.name = None

    # Make sure all expected financial metrics exist.
    expected_metrics = [
        "assets",
        "liabilities",
        "equity",
        "cash",
        "revenue",
        "operating_income",
        "net_income",
    ]

    for metric in expected_metrics:
        if metric not in gold_df.columns:
            gold_df[metric] = pd.NA

    # Keep a consistent column order.
    gold_df = gold_df[[
        "company",
        "company_cik",
        "fiscal_year",
        "assets",
        "liabilities",
        "equity",
        "cash",
        "revenue",
        "operating_income",
        "net_income",
    ]]

    # Sort chronologically within each company.
    gold_df = gold_df.sort_values(["company", "fiscal_year"]).reset_index(drop=True)

    return gold_df
