import json
import pandas as pd
from pathlib import Path

def load_raw_company_facts(file_path: str | Path) -> dict:
    """
    Load a raw Company Facts JSON file previously downloaded
    from the SEC API.

    Parameters
    ----------
    file_path : str | Path
        Path to the raw SEC JSON file.

    Returns
    -------
    dict
        Company Facts data loaded into a Python dictionary.
    """

    # Open the raw JSON file using UTF-8 encoding.
    with open(file_path, "r", encoding="utf-8") as file:
        data = json.load(file)

    # Return the complete raw SEC response as a dictionary.
    return data


def parse_concept_records(data: dict, concept: str, unit: str = "USD") -> list[dict]:
    """
    Extract all records for a specific US GAAP financial concept
    and unit from the SEC Company Facts data.

    Parameters
    ----------
    data : dict
        Raw Company Facts data obtained from the SEC API.

    concept : str
        US GAAP concept to extract.
        Examples:
        - Revenue
        - Assets
        - Liabilities
        - NetIncomeLoss

    unit : str
        Unit associated with the concept.
        Defaults to "USD".

    Returns
    -------
    list[dict]
        List of normalized financial records containing company,
        concept, period, value, filing and fiscal information.
    """

    # Access the US GAAP section of the SEC Company Facts response.
    us_gaap = data["facts"]["us-gaap"]

    # Select the requested financial concept.
    concept_data = us_gaap[concept]

    # Select the records corresponding to the requested unit.
    records = concept_data["units"][unit]

    # List that will contain the normalized records.
    parsed_records = []

    # Iterate through every SEC record associated with the concept.
    for record in records:

        # Transform the original SEC structure into a flat record.
        # This makes the data easier to work with using Pandas,
        # SQL databases or other downstream processing tools.
        parsed_record = {
            "company_cik": data["cik"],
            "entity_name": data["entityName"],
            "concept": concept,
            "unit": unit,
            "start_date": record.get("start"),
            "end_date": record.get("end"),
            "value": record["val"],
            "fiscal_year": record.get("fy"),
            "fiscal_period": record.get("fp"),
            "form": record.get("form"),
            "accession_number": record.get("accn"),
            "filed_date": record.get("filed"),
            "frame": record.get("frame"),
        }

        # Add the normalized record to the output list.
        parsed_records.append(parsed_record)

    return parsed_records


def parse_financial_facts(data: dict, concepts: list[str], unit: str = "USD") -> list[dict]:
    """
    Extract multiple financial concepts from SEC Company Facts data.

    Parameters
    ----------
    data : dict
        Raw Company Facts data obtained from the SEC API.

    concepts : list[str]
        List of US GAAP concepts to extract.

    unit : str
        Unit associated with the concepts.
        Defaults to "USD".

    Returns
    -------
    list[dict]
        Combined list containing records for all requested concepts.
    """

    # List that will contain records for every requested concept.
    all_records = []

    # Process each financial concept independently.
    for concept in concepts:
        records = parse_concept_records(data, concept, unit)
        all_records.extend(records)

    return all_records


def create_financial_dataframe(financial_records: list[dict]) -> pd.DataFrame:
    """
    Convert normalized financial records into a Pandas DataFrame
    and apply basic data type transformations.

    Parameters
    ----------
    financial_records : list[dict]
        Normalized financial records generated by
        parse_financial_facts().

    Returns
    -------
    pd.DataFrame
        Structured financial dataset ready for further processing
        or storage.
    """

    # Convert the list of dictionaries into a tabular DataFrame.
    df = pd.DataFrame(financial_records)

    # Columns containing dates that need to be converted.
    date_columns = ["start_date", "end_date", "filed_date",]

    # Convert all date columns to datetime.
    for column in date_columns:
        df[column] = pd.to_datetime(df[column])

    # Ensure that financial values are stored as numeric data.
    df["value"] = pd.to_numeric(df["value"])

    # Store the CIK as a string.
    # This is important because CIKs are identifiers rather than
    # numerical values and may contain leading zeros.
    df["company_cik"] = df["company_cik"].astype(str)

    return df


def save_financial_dataframe(df: pd.DataFrame, output_path: str | Path = "data/processed/financial_facts.csv") -> Path:
    """
    Save the processed financial DataFrame as a CSV file.

    Parameters
    ----------
    df : pd.DataFrame
        Processed financial dataset.

    output_path : str | Path
        Destination path for the CSV file.
        Defaults to "data/processed/financial_facts.csv".

    Returns
    -------
    Path
        Path to the generated CSV file.
    """

    # Convert the output path to a Path object for easier
    # cross-platform file handling.
    output_path = Path(output_path)

    # Create the parent directory if it does not already exist.
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Save the DataFrame as CSV.
    # index=False prevents Pandas from adding its own index column.
    df.to_csv(output_path, index=False)

    return output_path